export const timelineEntries = [{
    title: "In the '60's and '70's, researchers build up evidence...",
    subtitle: "for the role of decoding and phono- logical awareness.",
    id: 0,
    nestlevel: "1",
    has_subitems: false,
    subitems: [],
    has_XPs: false,
    XPs: [],
    Question: "",
    answer_type: "mc",
    option1: "",
    option2: "",
    option3: "",
    option4: "",
    closingText: "",
    closingText2: "",
    modal: ""
}, {
    title: "In the '60's and '70's, researchers build up evidence...",
    subtitle: "for the role of decoding and phono- logical awareness.",
    id: 0,
    nestlevel: "1",
    has_subitems: false,
    subitems: [],
    has_XPs: false,
    XPs: [],
    Question: "",
    answer_type: "mc",
    option1: "",
    option2: "",
    option3: "",
    option4: "",
    closingText: "",
    closingText2: "",
    modal: ""
}]